### ISSUE TITLE
不知道你會不會看 email 所以就發這裡了

### ISSUE THREAD

**Issue by as535364** [PwzXxm/PwzXxm.github.io#1]
# 關於交換連接
我的 [Blog](https://code.ujoj.cc) 想要申請交換連接
不知你覺得如何？

**Comment by PwzXxm** [comment]
你好呀，你说的交换链接是互相挂对方网站的链接在自己blog上吗？
可以的呀，不过我暂时还没有这个板块在我blog上。过段时间加可以吗？
BTW, 我看邮件的哈哈哈 :)

**Comment by as535364** [comment]
對喔
可你弄好版之後這邊說個，我就會收到通知了。
XD

**Comment by PwzXxm** [comment]
好啦 你可以看看[这里](http://www.pwzxxm.com/friendsblogs/)  麻烦你Blog上也加下咯  谢啦～

**Comment by as535364** [comment]
OK 我也加上了 [這裡](https://code.ujoj.cc/links/) 謝謝囉
